### PR TITLE
Adds answers

### PR DESCRIPTION
**Pull request by cadmiumcat**
This example was in a separate branch, but can live in the main one.

### CODE REVIEW

**Comment by mikeAdamss** [comment]
Closing, because no it can't. For the same reason you don't put the answers to exam questions on the back of the exam.

Not wanting to use a branch (fair enough, that's not what they're for) doesn't make this a good idea.

**Comment by cadmiumcat** [comment]
I disagree. I don't think this is intended to test our colleagues. And I believe they are able to view the answers... even if they're in a different branch. 

I'd appreciate a second opinion

**Comment by mikeAdamss** [comment]
It's intended as a playground, to let them try out what they're learned. Which is a little redundant if you give them something to copy-paste.

But fair enough, lets get a second opinion.

**Comment by cadmiumcat** [comment]
But... it's in a different file

**Comment by CharlesRendle** [comment]
I think that having answers available would remove the incentive to keep playing around and ask questions.

That could make the learning process a little longer and I think there's a happy medium with the well-commented walkthrough transformations which are always available to be used for reference.

**Comment by cadmiumcat** [comment]
@CharlesRendle - the answers are available even if they're in a different branch

**Comment by cadmiumcat** [comment]
`git checkout answers`

**Comment by mikeAdamss** [comment]
I agree that's a bad solution cat, I'm just not quite following how that makes merging it into master a good one.

By way of resolution, how about?
* I move the example elsewhere.
* I (re)close this PR.
* I delete the surplus branches.

Part of the upcoming documentation tasks will included making some better beginner resources anyway, so this would seem to solve your immediate concern.

**Comment by mikeAdamss** [comment]
discussed with Catalina. Will close but move the answers elsewhere so we can clean up the git branches a bit.

**Pull request closed without merging**
